server:
  port: ${PORT:8793}
message: Configuración de Gestión de Proyectos en el servidor levantado!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vivafia2?serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      uri: http://localhost:8081

feign:
  client:
    config:
      ms-management-faculties-schools:
        url: http://localhost:8792
      ms-academic-management:
        url: http://localhost:8791

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
