# ms-project-management.yml
server:
  port: ${PORT:8793}

message: Configuración de Gestión de usuarios en el servidor levantado!

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vivafia2?serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      escuela:
        url: http://localhost:8792
      facultad:
        url: http://localhost:8792
      semestre:
        url: http://localhost:8791
